credentials:
  usernames:
    test@company.com: # 여기 있는 test@company.com를 아이디로, 1234를 비밀번호로 입력하면 됨
      email: test@company.com
      name: 이사원
      password: $2b$12$JFK9VECbvo6A3OTAYDKjMuMvGoC8Dxi7FRSRUwVjYNnnEwGrjKSJa # 1234 해시값
      logged_in: False

    manager@company.com: 
      email: manager@company.com
      name: 김부장
      password: $2b$12$JFK9VECbvo6A3OTAYDKjMuMvGoC8Dxi7FRSRUwVjYNnnEwGrjKSJa # 비밀번호: 1234 (테스트용 동일)
      logged_in: False

cookie:
  expiry_days: 30 # 30일간 재로그인 안 해도 됨 # 로그아웃하면 초기화
  key: random_key
  name: law_chatbot_cookie